/*****************************************************************************
* Model: coffeeclock.qm
* File:  ./ao_masterswitch.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::ao_masterswitch.h} ..................................................*/
#ifndef MASTER_SWITCH_H
#define MASTER_SWITCH_H


#if ((QP_VERSION < 580) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpn version 5.8.0 or higher required
#endif

/*${AOs::MasterSwitch} .....................................................*/
typedef struct MasterSwitch {
/* protected: */
    QActive super;
} MasterSwitch;

/* protected: */
QState MasterSwitch_initial(MasterSwitch * const me);
QState MasterSwitch_on(MasterSwitch * const me);
QState MasterSwitch_off(MasterSwitch * const me);
QState MasterSwitch_wait briefly(MasterSwitch * const me);


#endif // MASTER_SWITCH_H
