/*****************************************************************************
* Model: coffeeclock.qm
* File:  ./arm_button.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::arm_button.h} .......................................................*/
#ifndef ARM_BUTTON_H
#define ARM_BUTTON_H


#if ((QP_VERSION < 580) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpn version 5.8.0 or higher required
#endif

/*${AOs::ArmButton} ........................................................*/
typedef struct ArmButton {
/* protected: */
    QActive super;
} ArmButton;

/* protected: */
QState ArmButton_initial(ArmButton * const me);
QState ArmButton_unpressed(ArmButton * const me);
QState ArmButton_pressed(ArmButton * const me);
QState ArmButton_waiting_for_release(ArmButton * const me);
QState ArmButton_after_release(ArmButton * const me);


#endif // ARM_BUTTON_H
