/*****************************************************************************
* Model: coffeeclock.qm
* File:  ./clock.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::clock.h} ............................................................*/
#ifndef CLOCK_H
#define CLOCK_H


#if ((QP_VERSION < 580) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpn version 5.8.0 or higher required
#endif

/*${AOs::Clock} ............................................................*/
typedef struct Clock {
/* protected: */
    QActive super;

/* private: */
    uint8_t alarm_hours;
    uint8_t alarm_minutes;
    uint8_t time_hours;
    uint8_t time_minutes;
} Clock;

/* protected: */
QState Clock_initial(Clock * const me);
QState Clock_on(Clock * const me);
QState Clock_alarm(Clock * const me);
QState Clock_set_minutes(Clock * const me);
QState Clock_minutes_blink_on(Clock * const me);
QState Clock_minutes_blink_off(Clock * const me);
QState Clock_show_alarm(Clock * const me);
QState Clock_set_hours(Clock * const me);
QState Clock_hours_blink_on(Clock * const me);
QState Clock_hours_blink_off(Clock * const me);
QState Clock_time(Clock * const me);
QState Clock_disconnected(Clock * const me);
QState Clock_off(Clock * const me);


#endif // CLOCK_H
